### ISSUE TITLE
Definitions for SemEval-2018 Task 9 Dataset

### ISSUE THREAD

**Issue by feudor2** [VityaVitalich/UniTax#2]
Hello, @VityaVitalich !

I'm having some troubles trying to reproduce your model's performance on SemEval-2018 Task 9 "1A: English" dataset after completing the fine-tuning procedure. Could you please help me clarify two points?

In your [paper](https://www.semantic-web-journal.net/system/files/swj3751.pdf) you mention that you achieved the best results by incorporating into prompts definitions for both train set (extracted from WordNet) and test sets. For the latter the definitions are said to be extracted from either WordNet or Wikidata or generated by Chat-GPT. You specify that you relied on external definitions in Taxonomy Enrichment and Lexical Entailment tasks, but you do not reveal what was your strategy for SemEval-2018. However, this dataset has no predetermined definitions and only two-thirds of its items are present in WordNet 3.1. Here arise two questions.

1. Did you actually use any externally acquired definitions in your Hypernym Extraction task?
2. If so, are these definitions available anywhere? In your [Data folder](https://drive.google.com/drive/folders/1nBCW9KlA77SDggn7MqZ3S4NOn4mAD36W) you provide SemEval-2018 test subsets with no "child_def" field, and in the repo I found no clue how you could have filled it.

I'd be grateful if you could share your definitions or correct me if I misunderstood something

Sincerely,
Feudor

**Comment by VityaVitalich** [comment]
Hello, Feudor!

For SemEval-2018 Task 9, definitions were not used. The training setup and data are already structured in a way that allows you to infer hypernyms directly. However, I believe incorporating definitions could provide additional benefits.

We didn’t extract definitions for this task because the words are often situated within a specific domain, which LLMs can quickly understand. This is further supported by the observed quality improvements when few-shot learning or slight fine-tuning is applied.

Hope this helps!

**Comment by feudor2** [comment]
Thank you, now it's much clearer!
